### ISSUE TITLE
Support for "--download-archive"

### ISSUE THREAD

**Issue by tjesp** [hstr0100/GDownloader#4]
Is it possible you can add support for "--download-archive" to prevent downloading the same file twice?

**Comment by hstr0100** [comment]
Done! By default, it will store the archive file in the same directory as the [config files](https://github.com/hstr0100/GDownloader?tab=readme-ov-file#platform-specific-configuration-file-locationsl). If that’s not what you had in mind, please let me know.

I’ll be publishing a new release with that feature later today.
